#%RAML 0.8
title: Polliwog
baseUri: http://polliwog-app.herokuapp.com/api/
documentation:
  - title: Overview
    content: |
      # TODO IN MARKDOWN
  - title: Getting started
    content: |
      # TODO IN MARKDOWN
  - title: The Privacy Rule
    content: |
      # TODO IN MARKDOWN
  - title: User Roles
    content: |
      # TODO IN MARKDOWN
  - title: Public & private lectures
    content: |
      # TODO IN MARKDOWN
  - title: Concept of Moods
    content: |
      # TODO IN MARKDOWN
  - title: Polls, questions & choices
    content: |
      # TODO IN MARKDOWN
  - title: Contributors
    content: |
      * Eléonore d'Agostino ([paranoodle](https://github.com/paranoodle))
      * Karim Ghozlani ([gweezer7](https://github.com/gweezer7))
      * Yassin Kammoun ([yibnl](https://github.com/yibnl))
      * Paul Ntawuruhunga ([paulnta](https://github.com/paulnta))
schemas:
  - lecture: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "key": {
            "type": "string",
            "unique": true
          },
          "name": {
            "type": "string",
            "required": true,
            "maxlength": 30
          },
          "description": {
            "type": "string",
            "required": true,
            "maxlength": 120
          },
          "creationDate": {
            "type": "date",
            "default": "date.now"
          },
          "isPrivate": {
            "type": "boolean",
            "default": false
          },
          "speaker": {
            "$ref": "user"
          },
          "listeners": {
            "type": "array",
            "items": {"$ref": "user"}
          },
          "moods": {
            "type": "array",
            "items": {"$ref": "mood"}
          },
          "polls": {
            "type": "array",
            "items": {"$ref": "poll"}
          },
          "resources": {
            "type": "array",
            "items": {"$ref": "resource"}
          }
        }
      }
  - poll: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "lecture": {
            "$ref": "lecture",
            "required": "true"
          },
          "title": {
            "type": "string",
            "required": "true"
          },
          "creationDate": {
            "type": "date",
            "default": "date.now"
          },
          "state": {
            "type": "string",
            "default": "draft",
            "enum": ["draft", "active", "closed"]
          },
          "questions": {
            "type": "array",
            "items": {"$ref": "question"}
          }
        }
      }
  - question: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "poll": {
            "$ref": "poll",
            "required": "true"
          },
          "title": {
            "type": "string",
            "required": "true"
          },
          "type": {
            "type": "string"
          },
          "choices": {
            "type": "array",
            "items": {"$ref": "choice"}
          }
        }
      }
  - choice: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "question": {
            "$ref": "question",
            "required": "true"
          },
          "key": {
            "type": "string",
            "required": "true"
          },
          "text": {
            "type": "string",
            "required": "true"
          },
          "answer_count": {
            "type": "number",
            "default": "0"
          }
        }  
      }
  - mood: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true,
        "properties": {
          "lecture": {
            "$ref": "lecture",
            "required": "true"
          },
          "date": {
            "type": "number",
            "required": "true"
          },
          "value": {
            "type": "number",
            "required": "true"
          },
          "reason": {
            "type": "string"
          }
        }  
      }
resourceTypes:
  - collection:
      get:
        description: Get list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleCollection>>
          400:
            description: Query parameters missing.
            body:
              application/x-www-form-urlencoded:
                example:
                  Bad Request
          500:
            description: An internal error occured.
      post:
        description: Create a new <<resourcePathName|!singularize>>.
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<examplePostPutItem>>
        responses:
          201:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          400:
            description: It is returned when required query parameters are missing.
            body:
              application/x-www-form-urlencoded:
                example:
                  Bad Request
          404:
            description: The resource has not been found.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Found
          409:
            description: It is returned when a POST request is submitted and an equivalent resource already exists.
            body:
              application/x-www-form-urlencoded:
                example:
                  Conflict
  - collection-item:
      get:
        description: |
          Get the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id = {<<resourcePathName|!singularize>>Id}.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          404:
            description: The resource has not been found.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Found
      put:
        description: |
          Update the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id = {<<resourcePathName|!singularize>>Id}.
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<examplePostPutItem>>
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          400:
            description: It is returned when required query parameters are missing.
            body:
              application/x-www-form-urlencoded:
                example:
                  Bad Request
          404:
            description: The resource has not been found.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Found
      patch:
        description: |
          Update partially the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id = {<<resourcePathName|!singularize>>Id}.
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<examplePostPutItem>>
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          400:
            description: It is returned when required query parameters are missing.
            body:
              application/x-www-form-urlencoded:
                example:
                  Bad Request
          404:
            description: The resource has not been found.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Found
      delete:
        description: |
          Delete the <<resourcePathName|!singularize>> with <<resourcePathName|!singularize>>Id = {<<resourcePathName|!singularize>>Id}.
        responses:
          204:
            description: It is returned when a DELETE request is submitted and succeed.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Content
          404:
            description: The resource has not been found.
            body:
              application/x-www-form-urlencoded:
                example:
                  Not Found
/lectures:
  type:
    collection:
      exampleCollection: |
        [
          {
            _id: 's1',
            key: 'BF2DG',
            name: 'HEIGVD-TWEB-2015-Lecture1',
            description: 'Introducing TWEB course to students',
            creationDate: 'Sun, 06 Nov 1994 08:49:37 GMT',
            isPrivate: true,
            speaker: 'sp1',
            listeners: [
              '/lectures/s1/users/u1',
              '/lectures/s1/users/u2',
              '/lectures/s1/users/u3',
            ],
            moods: [],
            polls: [
              '/lectures/s1/polls/p1',
              '/lectures/s1/polls/p2',
              '/lectures/s1/polls/p3',
            ],
            resources: [
              '/lectures/s1/resources/r1',
              '/lectures/s1/resources/r2',
              '/lectures/s1/resources/r3',

          },
          {
            _id: 's2',
            key: 'XY12SG',
            name: 'HEIGVD-TWEB-2015-Lecture2',
            description: 'Introducing Javascript basics to students',
            creationDate: 'Sun, 13 Nov 1994 08:49:37 GMT',
            isPrivate: true,
            speaker: 'sp1',
            listeners: [
              '/lectures/s2/users/u1',
              '/lectures/s2/users/u2',
              '/lectures/s2/users/u3',
            ],
            moods: [],
            polls: [
              '/lectures/s2/polls/p4',
              '/lectures/s2/polls/p5',
              '/lectures/s2/polls/p6',
            ],
            resources: [
              '/lectures/s2/resources/r4',
              '/lectures/s2/resources/r5',
              '/lectures/s2/resources/r6',

          },
          {
            _id: 's3',
            key: 'T89ADS',
            name: 'HEIGVD-TWEB-2015-Lecture3',
            description: 'Introducing api-copilot testing tool to students',
            creationDate: 'Sun, 20 Nov 1994 08:49:37 GMT',
            isPrivate: true,
            speaker: 'sp1',
            listeners: [
              '/lectures/s3/users/u1',
              '/lectures/s3/users/u2',
              '/lectures/s3/users/u3',
            ],
            moods: [],
            polls: [
              '/lectures/s3/polls/p7',
              '/lectures/s3/polls/p8',
              '/lectures/s3/polls/p9',
            ],
            resources: [
              '/lectures/s3/resources/r7',
              '/lectures/s3/resources/r8',
              '/lectures/s3/resources/r9',
            ]
          }
        ]
      examplePostPutItem: |
        {
          'name': 'HEIGVD-TWEB-2015-Lecture1',
          'description': 'Introducing TWEB course to students',
          'isPrivate': true,
        }
      exampleItem: |
        {
          _id: 's1',
          key: 'BF2DG',
          name: 'HEIGVD-TWEB-2015-Lecture1',
          description: 'Introducing TWEB course to students',
          creationDate: 'Sun, 06 Nov 1994 08:49:37 GMT',
          isPrivate: true,
          speaker: 'sp1',
          listeners: [],
          moods: [],
          polls: [],
          resources: []
        }
  /{lectureId}:
    type:
      collection-item:
        examplePostPutItem: |
          {
            'description': 'Introducing TWEB course to third year students',
          }
        exampleItem: |
          {
            _id: 's1',
            key: 'BF2DG',
            name: 'HEIGVD-TWEB-2015-Lecture1',
            description: 'Introducing TWEB course to third year students',
            creationDate: 'Sun, 06 Nov 1994 08:49:37 GMT',
            isPrivate: true,
            speaker: 'sp1',
            listeners: [
              '/lectures/s1/users/u1',
              '/lectures/s1/users/u2',
              '/lectures/s1/users/u3',
            ],
            moods: [],
            polls: [
              '/lectures/s1/polls/p1',
              '/lectures/s1/polls/p2',
              '/lectures/s1/polls/p3',
            ],
            resources: [
              '/lectures/s1/resources/r1',
              '/lectures/s1/resources/r2',
              '/lectures/s1/resources/r3',
          }
    /polls: 
      type:
        collection:
          exampleCollection: |
            [
              {
                '_id': 'p1',
                'lecture': '/lectures/s1',
                'title': 'TWEB-2015',
                'creationDate': '2015-05-02 10:41' ,
                'state': 'draft',
                'questions': 
                  [
                    '/lectures/s1/polls/p1/questions/q1',
                    '/lectures/s1/polls/p1/questions/q2',
                    '/lectures/s1/polls/p1/questions/q3'
                  ]
              },
              {
                '_id': 'p2',
                'lecture': '/lectures/s1',
                'title': 'AMT-2015',
                'creationDate': '2015-11-25 14:03',
                'state': 'active',
                'questions': 
                  [
                    '/lectures/s1/polls/p2/questions/q11',
                    '/lectures/s1/polls/p2/questions/q22',
                    '/lectures/s1/polls/p2/questions/q32'
                  ]
              },
              {
                '_id': 'p3',
                'lecture': '/lectures/s2',
                'title': 'RES-2015',
                'creationDate': '2015-12-12 12:00', 
                'state': 'closed',
                'questions': 
                  [
                    '/lectures/s2/polls/p3/questions/q13',
                    '/lectures/s2/polls/p3/questions/q23',
                    '/lectures/s2/polls/p3/questions/q33'
                  ]
              }
            ]
          examplePostPutItem: |
            {
              'title': 'TWEB-2015', 
              'state': 'draft'
            }
          exampleItem: |
            {
                '_id': 'p2',
                'lecture': '/lectures/s1',
                'title': 'TWEB-2015',
                'creationDate': '2015-11-25 14:03',
                'state': 'draft',
                'questions': []
              },
      /{pollId}:
        type:
          collection-item:
            examplePostPutItem: |
              {
                'title': 'TWEB-2015', 
                'state': 'draft'
              }
            exampleItem: |
              {
                '_id': 'p1',
                'lecture': '/lectures/s1',
                'title': 'TWEB-2015', 
                'creationDate': '2015-11-02 09:41'
                'state': 'draft',
                'questions': 
                    [
                      '/lectures/s1/polls/p1/questions/q1',
                      '/lectures/s1/polls/p1/questions/q2',
                      '/lectures/s1/polls/p1/questions/q3'
                    ]
              }
        /questions: 
          type:
            collection:
              exampleCollection: |
                [
                  {
                    '_id': 'q1',
                    'poll': 'p1',
                    'title': 'What is a scenario ?',
                    'type': 'reminder' 
                    'choices':
                      [
                        '/lectures/s1/polls/p1/questions/q1/choice/c1',
                        '/lectures/s1/polls/p1/questions/q1/choice/c2',
                        '/lectures/s1/polls/p1/questions/q1/choice/c3'
                      ]
                  },
                  {
                    '_id': 'q2',
                    'poll': 'p1',
                    'title': ''How do you run a scenario ?',
                    'type': 'reminder' 
                    'choices':
                      [
                        '/lectures/s1/polls/p1/questions/q2/choice/c4',
                        '/lectures/s1/polls/p1/questions/q2/choice/c5',
                        '/lectures/s1/polls/p1/questions/q2/choice/c6'
                      ]
                  },
                  {
                    '_id': 'q3',
                    'poll': 'p1',
                    'title': 'Who is the author of the API Copilot',
                    'type': 'reminder' 
                    'choices':
                      [
                        '/lectures/s1/polls/p1/questions/q3/choice/c7',
                        '/lectures/s1/polls/p1/questions/q3/choice/c8',
                        '/lectures/s1/polls/p1/questions/q3/choice/c9'
                      ]
                  }
                ]
              examplePostPutItem: |
                {
                  'title': 'What is a scenario ?',
                  'type': 'reminder' 
                }
              exampleItem: |
                {
                  '_id': 'q1',
                  'poll': 'p1',
                  'title': 'What is a scenario ?',
                  'type': 'reminder' 
                  'choices': []
                }
          /{questionId}:
            type:
              collection-item:
                examplePostPutItem: |
                  {
                    'title': 'What is a scenario ?',
                    'type': 'reminder' 
                  }
                exampleItem: |
                  {
                    '_id': 'q1',
                    'poll': 'p1',
                    'title': 'What is a scenario ?',
                    'type': 'reminder' 
                    'choices':
                      [
                        '/lectures/s1/polls/p1/questions/q1/choice/c1',
                        '/lectures/s1/polls/p1/questions/q1/choice/c2',
                        '/lectures/s1/polls/p1/questions/q1/choice/c3'
                      ]
                  }
            /choices:
              type:
                collection:
                  exampleCollection: |
                    [
                      {
                        '_id': 'c1',
                        'question': 'q1',
                        'key': 'a', 
                        'text': 'A setting, in particular for a work of art or literature.',
                        'answer_count': '0'
                      },
                      {
                        '_id': 'c2',
                        'question': 'q1',
                        'key': 'b', 
                        'text': 'A series of steps that are executed in order using the "step" method.',
                        'answer_count': '3'
                      }
                      ,{
                        '_id': 'c3',
                        'question': 'q1',
                        'key': 'c', 
                        'text': 'A written outline of a film, novel, or stage work giving details of the plot and individual scenes.',
                        'answer_count': '0'
                      }
                    ]
                  examplePostPutItem: |
                    {
                      'key': 'b', 
                      'text': 'A series of steps that are executed in order using the "step" method.'
                    }
                  exampleItem: |
                    {
                      '_id': 'c2',
                      'question': 'q1',
                      'key': 'b', 
                      'text': 'A series of steps that are executed in order using the "step" method.',
                      'answer_count': '0'
                    }
              /{choiceId}:
                type:
                  collection-item:
                    examplePostPutItem: |
                      {
                        'key': 'b', 
                        'text': 'A series of steps that are executed in order using the "step" method.'
                      }
                    exampleItem: |
                      {
                        '_id': 'c1',
                        'question': 'q1',
                        'key': 'b', 
                        'text': 'A series of steps that are executed in order using the "step" method.',
                        'answer_count': '0'
                      }
    /resources:
      type:
        collection:
          exampleCollection: |
            [
              {
                '_id': 'r1',
                'lecture': 's1',
                'title': 'Lorem ipsum',
                'subhead': 'Lorem ipsum dolor sit amet',
                'creationDate': 'Sun, 06 Nov 1994 08:49:37 GMT', 
                'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
                'file': ''
              },
              {
                '_id': 'r2',
                'lecture': 's1',
                'title': 'Lorem ipsum',
                'subhead': 'Lorem ipsum dolor sit amet',
                'creationDate': 'Sun, 06 Nov 1994 08:49:37 GMT', 
                'text': '',
                'file': 'https://www.dropbox.com/s/qmocfrco2t0d28o/Fluffbeast.docx'
              },
              {
                '_id': 'r3',
                'lecture': 's1',
                'title': 'Lorem ipsum',
                'subhead': 'Lorem ipsum dolor sit amet',
                'creationDate': 'Sun, 06 Nov 1994 08:49:37 GMT', 
                'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
                'file': 'https://www.dropbox.com/s/qmocfrco2t0d28o/Fluffbeast.docx'
              }
            ]
          examplePostPutItem: |
            {
              'title': 'Lorem ipsum',
              'subhead': 'Lorem ipsum dolor sit amet',
              'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
              'file': 'https://www.dropbox.com/s/qmocfrco2t0d28o/Fluffbeast.docx'
            }
          exampleItem: |
            {
              '_id': 'r3',
              'lecture': 's1',
              'title': 'Lorem ipsum',
              'subhead': 'Lorem ipsum dolor sit amet',
              'creationDate': 'Sun, 06 Nov 1994 08:49:37 GMT', 
              'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
              'file': 'https://www.dropbox.com/s/qmocfrco2t0d28o/Fluffbeast.docx'
            }
      /{resourceId}:
        type:
          collection-item:
            examplePostPutItem: |
              {
                'title': 'Ipsum lorem '
              }
            exampleItem: |
              {
                '_id': 'r1',
                'lecture': 's1',
                'title': 'Ipsum lorem ',
                'subhead': 'Lorem ipsum dolor sit amet',
                'creationDate': 'Sun, 06 Nov 1994 08:49:37 GMT', 
                'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
                'file': 'https://www.dropbox.com/s/qmocfrco2t0d28o/Fluffbeast.docx'
              }
    /moods:
      type:
        collection:
          exampleCollection: |
            []
          examplePostPutItem: |
            {}
          exampleItem: |
            {}
      /{moodId}:
        type:
          collection-item:
            examplePostPutItem: |
              {}
            exampleItem: |
              {}